name: cell2mol
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - bleach=4.1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.0
  - contourpy=1.0.5
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - fontconfig=2.14.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.19.8.1
  - glib=2.74.0
  - glib-tools=2.74.0
  - greenlet=1.1.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - icu=70.1
  - importlib-metadata=4.11.3
  - iniconfig=1.1.1
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyter_server=1.17.0
  - jupyterlab=3.4.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - jupyterlab_widgets=3.0.3
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20210910
  - libffi=3.4.2
  - libflac=1.3.4
  - libgfortran5=11.3.0
  - libglib=2.74.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.38
  - libpq=14.5
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libsqlite=3.39.4
  - libtiff=4.4.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.1.1
  - matplotlib-base=3.6.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - munkres=1.1.4
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclient=0.7.0
  - nbconvert=7.2.1
  - nbconvert-core=7.2.1
  - nbconvert-pandoc=7.2.1
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=2.8.7
  - notebook=6.4.12
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.1
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.5.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - pluggy=1.0.0
  - ply=3.11
  - portaudio=19.6.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.31
  - psutil=5.9.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - py3dmol=1.8.1
  - pycairo=1.21.0
  - pycifrw=4.4.3
  - pycparser=2.21
  - pygments=2.13.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.1
  - pytest=7.1.3
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytz=2022.4
  - pyzmq=24.0.1
  - qt-main=5.15.6
  - qtconsole=5.3.2
  - qtconsole-base=5.3.2
  - qtpy=2.2.1
  - rdkit=2022.03.5
  - readline=8.1.2
  - reportlab=3.5.68
  - scipy=1.9.1
  - send2trash=1.8.0
  - setuptools=65.4.1
  - sip=6.7.2
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlalchemy=1.4.42
  - sqlite=3.39.4
  - stack_data=0.5.1
  - terminado=0.16.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.4.0
  - typing_extensions=4.4.0
  - tzdata=2022e
  - unicodedata2=14.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=4.0.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.9.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - cosymlib==0.10.9
    - huckelpy==0.2.3
    - pyyaml==6.0
    - symgroupy==0.5.10
    - wfnsympy==0.3.5
